DELETE FROM public.applications;
DELETE FROM public.jobs;
DELETE FROM public.companies;

INSERT INTO public.companies (slug, name, category, website_url, description, tagline, headquarters, mission, culture, benefits, hiring_process, is_partner) VALUES
('socar', '쏘카(SOCAR)', '모빌리티', 'https://socar.kr', '대한민국 1위 카셰어링 플랫폼.', '이동의 새로운 기준', '서울 성동구', '모든 사람이 자유롭게 이동하는 세상을 만듭니다.', '자율과 책임 기반의 수평적 문화', '["원격근무","자유로운 연차","쏘카 이용권","장비 지원"]'::jsonb, '["서류","코딩테스트","기술면접","컬쳐핏"]'::jsonb, true),
('toss', '토스(Toss)', '핀테크', 'https://toss.im', '금융을 간편하게. 대한민국 대표 핀테크 유니콘.', '금융의 모든 것을 쉽게', '서울 강남구', '누구나 쉽고 공정하게 금융 서비스를 이용하는 세상.', '최고의 인재가 최고의 결과를 만드는 팀', '["업계 최고 보상","자율 출퇴근","식대 무제한","건강검진"]'::jsonb, '["서류","과제","직무면접","리더면접"]'::jsonb, true),
('baemin', '우아한형제들(배민)', '푸드테크', 'https://woowahan.com', '배달의민족을 만드는 우아한형제들.', '좋은 음식을 먹고 싶은 곳에서', '서울 송파구', '배달을 통해 사람들의 일상을 더 편리하게.', '송파구에서 일을 더 잘하는 11가지 방법', '["주 35시간","배민 식대","도서비","건강관리"]'::jsonb, '["서류","직무면접","컬쳐핏면접"]'::jsonb, true),
('kakao', '카카오', '플랫폼', 'https://kakaocorp.com', '대한민국 대표 IT 플랫폼 기업.', '사람과 사람, 사람과 기술을 잇다', '경기 판교', '기술과 사람이 만드는 더 나은 세상.', '크루 중심의 자율적 조직 문화', '["자유로운 근무","장비 선택","교육비","헬스케어"]'::jsonb, '["서류","코딩테스트","기술면접","임원면접"]'::jsonb, true),
('naver', '네이버', '검색/AI', 'https://navercorp.com', '대한민국 1위 검색 포털. AI, 클라우드, 커머스까지.', '기술이 만드는 초연결 세상', '경기 판교', '기술로 세상의 불편함을 해결합니다.', '글로벌 수준의 R&D 중심 문화', '["유연근무제","사내 의료실","교육 프로그램","주거 지원"]'::jsonb, '["서류","코딩테스트","기술면접","팀면접"]'::jsonb, true),
('coupang', '쿠팡', '이커머스', 'https://coupang.com', '로켓배송의 쿠팡. 고객 경험을 혁신하는 이커머스 기업.', '쿠팡 없이 어떻게 살았을까', '서울 송파구', '고객이 와우할 수 있는 경험을 만듭니다.', 'Day 1 문화, 고객 집착', '["스톡옵션","중식 제공","셔틀버스","육아 지원"]'::jsonb, '["서류","온라인테스트","기술면접","바레이저"]'::jsonb, true),
('krafton', '크래프톤', '게임', 'https://krafton.com', 'PUBG를 만든 글로벌 게임 기업.', '즐거운 경험을 선사하는 크리에이티브 기업', '서울 강남구', '전 세계 게이머에게 즐거움을 전달합니다.', '몰입과 창의를 중시하는 문화', '["게임 구매 지원","건강검진","장비 최상급","글로벌 출장"]'::jsonb, '["서류","과제","기술면접","임원면접"]'::jsonb, true),
('smartmind-ai', '스마트마인드에이아이', 'AI', 'https://smartmindai.com', 'AI 기술로 기업의 디지털 전환을 돕는 AI 전문 기업.', 'AI로 더 스마트한 세상', '서울 서초구', '모든 기업이 AI를 활용할 수 있는 세상.', '연구와 실무가 함께하는 팀', '["유연근무","GPU 서버 무제한","논문 발표 지원","교육비"]'::jsonb, '["서류","기술면접","팀면접"]'::jsonb, true),
('bucketplace', '오늘의집', '인테리어', 'https://ohou.se', '인테리어부터 이사까지, 집에 관한 모든 것.', '집꾸미기의 모든 것', '서울 서초구', '누구나 예쁜 집에서 살 수 있는 세상.', '데이터 기반의 의사결정 문화', '["인테리어 지원금","자율출퇴근","식대","건강검진"]'::jsonb, '["서류","과제","직무면접","컬쳐핏"]'::jsonb, true),
('moloco', '몰로코(Moloco)', '애드테크', 'https://moloco.com', '머신러닝 기반 광고 최적화 플랫폼. 실리콘밸리 출신.', 'ML-powered advertising', '서울 강남구', '머신러닝으로 디지털 광고의 효율을 극대화합니다.', '글로벌 스타트업 문화, 영어 공용', '["RSU","원격근무","교육비 무제한","워케이션"]'::jsonb, '["서류","코딩테스트","시스템디자인","팀면접"]'::jsonb, true),
('daangn', '당근마켓', '로컬커뮤니티', 'https://daangn.com', '동네 이웃 간의 연결을 만드는 지역 생활 커뮤니티.', '당신 근처의 마켓', '서울 서초구', '가까운 이웃과 연결되는 따뜻한 동네를 만듭니다.', '자율과 신뢰 기반 조직 문화', '["자율출퇴근","원격근무","장비지원","건강검진"]'::jsonb, '["서류","과제","직무면접","컬쳐핏"]'::jsonb, true),
('sendbird', '센드버드', 'SaaS', 'https://sendbird.com', '글로벌 인앱 커뮤니케이션 API 기업.', 'Conversations that build relationships', '서울 강남구', '모든 앱에 대화 기능을 쉽게 연동합니다.', '실리콘밸리 스타일의 글로벌 팀', '["RSU","영어 교육","장비 선택","워케이션"]'::jsonb, '["서류","기술면접","시스템디자인","컬쳐핏"]'::jsonb, true),
('hyperconnect', '하이퍼커넥트', 'AI/소셜', 'https://hyperconnect.com', 'AI 기술 기반 글로벌 소셜 디스커버리 플랫폼.', 'Connect Beyond Boundaries', '서울 서초구', 'AI와 비디오 기술로 전세계 사람들을 연결합니다.', '글로벌 환경, 다양성 존중', '["원격근무","어학 지원","RSU","장비 최상급"]'::jsonb, '["서류","코딩테스트","기술면접","팀면접"]'::jsonb, true),
('dunamu', '두나무(업비트)', '블록체인', 'https://dunamu.com', '업비트를 운영하는 핀테크 기업.', '투자를 더 쉽게', '서울 강남구', '블록체인 기술로 새로운 금융 인프라를 구축합니다.', '도전과 혁신을 장려하는 문화', '["업계 최고 보상","자율출퇴근","식대","건강관리"]'::jsonb, '["서류","기술면접","임원면접"]'::jsonb, true),
('channel-corp', '채널톡', 'SaaS', 'https://channel.io', '올인원 AI 메신저 솔루션.', '모든 비즈니스의 성장 파트너', '서울 강남구', '고객과 비즈니스 사이의 소통을 혁신합니다.', '실험과 학습을 중시하는 문화', '["원격근무","자율 연차","교육비","장비 지원"]'::jsonb, '["서류","과제","직무면접","컬쳐핏"]'::jsonb, true);

INSERT INTO public.jobs (slug, company_id, title, role, location, arrangement, experience_label, education_label, summary, description, responsibilities, requirements, perks, status, deadline_at) VALUES
('socar-ai-engineer', (SELECT id FROM companies WHERE slug='socar'), 'AI Engineer (Autonomous Mobility)', '개발', '서울 성동구', '하이브리드', '경력 3년+', '학사 이상', '자율주행 모빌리티 서비스를 위한 AI 모델을 설계하고 배포합니다.', '쏘카의 자율주행팀에서 인지/판단 모델을 개발합니다.', '["자율주행 인지 모델 개발","시뮬레이션 환경 구축","실차 테스트 및 성능 개선"]'::jsonb, '["딥러닝 프레임워크 활용 경험","Computer Vision 경험","Python, C++ 능숙"]'::jsonb, '["원격근무","쏘카 이용권","GPU 서버"]'::jsonb, 'published', now() + interval '30 days'),
('toss-frontend', (SELECT id FROM companies WHERE slug='toss'), 'Frontend Engineer', '개발', '서울 강남구', '하이브리드', '경력 3년+', '학사 이상', '토스 금융 서비스의 웹 프론트엔드를 개발합니다.', '수천만 사용자가 이용하는 금융 서비스 UI를 만듭니다.', '["React 기반 웹 애플리케이션 개발","성능 최적화","디자인 시스템 개선"]'::jsonb, '["React, TypeScript 숙련","웹 성능 최적화 경험","금융/핀테크 경험 우대"]'::jsonb, '["업계 최고 보상","자율출퇴근","식대 무제한"]'::jsonb, 'published', now() + interval '25 days'),
('toss-data-analyst', (SELECT id FROM companies WHERE slug='toss'), 'Data Analyst', '데이터', '서울 강남구', '하이브리드', '경력 2년+', '학사 이상', '데이터 기반 의사결정을 지원하는 분석을 수행합니다.', '토스의 핵심 지표를 분석하고 인사이트를 도출합니다.', '["핵심 비즈니스 지표 분석","대시보드 설계","A/B 테스트 설계"]'::jsonb, '["SQL 능숙","Python/R 분석 경험","통계적 사고"]'::jsonb, '["데이터 인프라 최상급","교육비 지원"]'::jsonb, 'published', now() + interval '20 days'),
('toss-security', (SELECT id FROM companies WHERE slug='toss'), 'Security Engineer', '보안', '서울 강남구', '하이브리드', '경력 3년+', '학사 이상', '토스 금융 서비스의 보안 인프라를 설계합니다.', '수천만 사용자의 금융 데이터를 보호합니다.', '["보안 아키텍처 설계","취약점 분석","인시던트 대응"]'::jsonb, '["보안 실무 3년+","금융 보안 이해","코드 리뷰 역량"]'::jsonb, '["업계 최고 보상","자율출퇴근"]'::jsonb, 'published', now() + interval '30 days'),
('baemin-backend', (SELECT id FROM companies WHERE slug='baemin'), 'Backend Engineer (주문시스템)', '개발', '서울 송파구', '하이브리드', '경력 3년+', '학사 이상', '배달의민족 주문 시스템의 백엔드를 개발합니다.', '초당 수만 건의 주문을 처리하는 대규모 시스템을 설계합니다.', '["주문/결제 시스템 개발","대규모 트래픽 처리","MSA 설계"]'::jsonb, '["Java/Kotlin 숙련","Spring 생태계","대규모 트래픽 경험"]'::jsonb, '["주 35시간","배민 식대","도서비"]'::jsonb, 'published', now() + interval '18 days'),
('baemin-designer', (SELECT id FROM companies WHERE slug='baemin'), 'Product Designer', '디자인', '서울 송파구', '하이브리드', '경력 2년+', '학사 이상', '배달의민족의 사용자 경험을 설계합니다.', '수천만 사용자의 일상에 닿는 제품을 디자인합니다.', '["UX/UI 디자인","프로토타이핑","사용자 리서치"]'::jsonb, '["Figma 능숙","모바일 서비스 디자인 경험","데이터 기반 디자인"]'::jsonb, '["주 35시간","디자인 컨퍼런스 지원"]'::jsonb, 'published', now() + interval '22 days'),
('baemin-marketing', (SELECT id FROM companies WHERE slug='baemin'), '브랜드 마케터', '마케팅', '서울 송파구', '하이브리드', '경력 3년+', '학사 이상', '배달의민족 브랜드 캠페인을 기획하고 실행합니다.', '배민다운 크리에이티브로 사랑받는 브랜드를 만듭니다.', '["브랜드 캠페인 기획","콘텐츠 전략 수립","외부 파트너 협업"]'::jsonb, '["브랜드 마케팅 경험 3년+","크리에이티브 기획력","트렌드 감각"]'::jsonb, '["주 35시간","배민 식대"]'::jsonb, 'published', now() + interval '15 days'),
('kakao-ml', (SELECT id FROM companies WHERE slug='kakao'), 'ML Engineer (추천시스템)', '개발', '경기 판교', '하이브리드', '경력 3년+', '석사 우대', '카카오 서비스의 추천 시스템을 개발합니다.', '수천만 사용자에게 최적의 콘텐츠를 추천합니다.', '["추천 모델 연구 및 개발","A/B 테스트 설계","대규모 추론 파이프라인"]'::jsonb, '["ML/DL 모델 개발 경험","Python, PyTorch","추천시스템 이해"]'::jsonb, '["자유로운 근무","GPU 클러스터","논문 지원"]'::jsonb, 'published', now() + interval '28 days'),
('kakao-devops', (SELECT id FROM companies WHERE slug='kakao'), 'DevOps Engineer', '개발', '경기 판교', '하이브리드', '경력 3년+', '학사 이상', '카카오 서비스의 CI/CD와 인프라를 운영합니다.', '안정적인 서비스 배포와 운영 자동화를 담당합니다.', '["CI/CD 파이프라인 구축","Kubernetes 운영","모니터링 시스템"]'::jsonb, '["DevOps 경험 3년+","Kubernetes, Terraform","Linux 시스템"]'::jsonb, '["자유로운 근무","장비 선택","교육비"]'::jsonb, 'published', now() + interval '28 days'),
('naver-cloud', (SELECT id FROM companies WHERE slug='naver'), 'Cloud Platform Engineer', '개발', '경기 판교', '하이브리드', '경력 5년+', '학사 이상', '네이버 클라우드 플랫폼의 핵심 인프라를 개발합니다.', '글로벌 클라우드 서비스의 안정성을 책임집니다.', '["클라우드 인프라 설계","Kubernetes 운영","자동화 파이프라인"]'::jsonb, '["클라우드 인프라 5년+","Kubernetes, Docker","Go/Python"]'::jsonb, '["유연근무제","사내 의료실","교육 프로그램"]'::jsonb, 'published', now() + interval '35 days'),
('naver-search-ai', (SELECT id FROM companies WHERE slug='naver'), 'Search & AI Researcher', '연구', '경기 판교', '하이브리드', '경력 무관', '석사 이상', 'LLM과 검색 기술의 차세대 연구를 수행합니다.', '네이버 검색의 AI 혁신을 이끄는 연구팀입니다.', '["LLM 기반 검색 연구","자연어 이해 모델","논문 발표"]'::jsonb, '["NLP/IR 연구 경험","탑 컨퍼런스 논문","PyTorch 능숙"]'::jsonb, '["연구 자율성","학회 참가","논문 인센티브"]'::jsonb, 'published', now() + interval '40 days'),
('coupang-sde', (SELECT id FROM companies WHERE slug='coupang'), 'Software Development Engineer', '개발', '서울 송파구', '오프라인', '경력 2년+', '학사 이상', '쿠팡의 핵심 커머스 시스템을 개발합니다.', '로켓배송을 가능하게 하는 기술을 만듭니다.', '["대규모 분산 시스템","API 설계 및 구현","성능 최적화"]'::jsonb, '["Java/Kotlin/Python","분산 시스템 이해","AWS 경험"]'::jsonb, '["스톡옵션","중식 제공","셔틀버스"]'::jsonb, 'published', now() + interval '30 days'),
('coupang-pm', (SELECT id FROM companies WHERE slug='coupang'), 'Product Manager (Logistics)', '기획', '서울 송파구', '오프라인', '경력 5년+', '학사 이상', '로켓배송 물류 시스템의 제품 기획을 맡습니다.', '배송 경험을 혁신하는 제품을 기획합니다.', '["물류 제품 로드맵","데이터 기반 의사결정","엔지니어링팀 협업"]'::jsonb, '["PM 경험 5년+","물류/이커머스 이해","데이터 분석"]'::jsonb, '["스톡옵션","성과 보너스"]'::jsonb, 'published', now() + interval '25 days'),
('krafton-server', (SELECT id FROM companies WHERE slug='krafton'), 'Game Server Engineer', '개발', '서울 강남구', '하이브리드', '경력 3년+', '학사 이상', 'PUBG 등 글로벌 게임의 서버를 개발합니다.', '수백만 동시접속을 처리하는 서버 시스템.', '["게임 서버 아키텍처","대규모 동시접속","실시간 네트워킹"]'::jsonb, '["C++/Go 서버 개발","네트워크 프로그래밍","게임 서버 경험 우대"]'::jsonb, '["게임 구매 지원","장비 최상급","글로벌 출장"]'::jsonb, 'published', now() + interval '32 days'),
('smartmind-data', (SELECT id FROM companies WHERE slug='smartmind-ai'), 'AI 데이터 엔지니어', '데이터', '서울 서초구', '하이브리드', '경력 2년+', '학사 이상', 'AI 모델 학습을 위한 데이터 파이프라인을 구축합니다.', 'LLM/ML 모델의 학습 데이터를 관리합니다.', '["데이터 파이프라인 설계","ETL 프로세스","데이터 품질 관리"]'::jsonb, '["Python, SQL 능숙","Airflow/Spark","ML 데이터 이해"]'::jsonb, '["유연근무","GPU 서버","교육비"]'::jsonb, 'published', now() + interval '20 days'),
('smartmind-orchestration', (SELECT id FROM companies WHERE slug='smartmind-ai'), 'AI Orchestration 개발자', '개발', '서울 서초구', '하이브리드', '경력 3년+', '학사 이상', 'AI 에이전트 워크플로우 오케스트레이션을 개발합니다.', 'LLM 기반 AI 에이전트 플랫폼을 만듭니다.', '["AI 에이전트 시스템 설계","LLM 통합 파이프라인","API 서비스"]'::jsonb, '["LLM/RAG 경험","Python, FastAPI","클라우드 배포"]'::jsonb, '["최신 AI 인프라","논문 발표 지원"]'::jsonb, 'published', now() + interval '25 days'),
('ohou-frontend', (SELECT id FROM companies WHERE slug='bucketplace'), '프론트엔드 엔지니어', '개발', '서울 서초구', '하이브리드', '경력 2년+', '학사 이상', '오늘의집 서비스의 웹 프론트엔드를 개발합니다.', '인테리어 커머스 플랫폼의 사용자 경험을 만듭니다.', '["React 기반 웹 개발","성능 최적화","접근성 개선"]'::jsonb, '["React, TypeScript","웹 성능 최적화","CSS-in-JS"]'::jsonb, '["인테리어 지원금","자율출퇴근"]'::jsonb, 'published', now() + interval '18 days'),
('moloco-ml', (SELECT id FROM companies WHERE slug='moloco'), 'Machine Learning Engineer', '개발', '서울 강남구', '하이브리드', '경력 3년+', '석사 우대', '광고 최적화를 위한 대규모 ML 시스템을 개발합니다.', '실시간 광고 입찰과 타겟팅을 위한 ML 파이프라인.', '["대규모 ML 시스템","실시간 추론","모델 성능 최적화"]'::jsonb, '["ML 시스템 설계","Python, C++","분산 시스템"]'::jsonb, '["RSU","원격근무","교육비 무제한"]'::jsonb, 'published', now() + interval '35 days'),
('daangn-backend', (SELECT id FROM companies WHERE slug='daangn'), 'Backend Engineer (커뮤니티)', '개발', '서울 서초구', '하이브리드', '경력 3년+', '학사 이상', '당근마켓 동네생활 서비스의 백엔드를 개발합니다.', '지역 커뮤니티 서비스의 핵심 기능을 만듭니다.', '["커뮤니티 서비스 개발","GraphQL API","검색/추천"]'::jsonb, '["Go/Kotlin","GraphQL","대규모 서비스 운영"]'::jsonb, '["자율출퇴근","원격근무","장비지원"]'::jsonb, 'published', now() + interval '22 days'),
('sendbird-fullstack', (SELECT id FROM companies WHERE slug='sendbird'), 'Full-Stack Engineer', '개발', '서울 강남구', '하이브리드', '경력 3년+', '학사 이상', '글로벌 메시징 API의 대시보드를 개발합니다.', '전세계 고객이 사용하는 관리 콘솔.', '["React/Node.js 풀스택","API 설계","내부 도구"]'::jsonb, '["React, Node.js","TypeScript","영어 커뮤니케이션"]'::jsonb, '["RSU","영어 교육","워케이션"]'::jsonb, 'published', now() + interval '28 days'),
('hyperconnect-ios', (SELECT id FROM companies WHERE slug='hyperconnect'), 'iOS Engineer', '개발', '서울 서초구', '하이브리드', '경력 3년+', '학사 이상', 'Azar, Hakuna 등 글로벌 소셜 앱의 iOS를 개발합니다.', '전세계 수억 사용자가 이용하는 앱.', '["Swift 기반 iOS 개발","실시간 영상통화","CI/CD"]'::jsonb, '["Swift/UIKit","영상 처리 경험 우대","글로벌 서비스"]'::jsonb, '["원격근무","RSU","어학 지원"]'::jsonb, 'published', now() + interval '30 days'),
('dunamu-blockchain', (SELECT id FROM companies WHERE slug='dunamu'), 'Blockchain Engineer', '개발', '서울 강남구', '하이브리드', '경력 3년+', '학사 이상', '업비트 거래 시스템의 블록체인 인프라를 개발합니다.', '안전하고 빠른 디지털 자산 거래 인프라.', '["블록체인 노드 운영","스마트 컨트랙트","보안 인프라"]'::jsonb, '["블록체인 개발 경험","Go/Rust","보안 지식"]'::jsonb, '["업계 최고 보상","자율출퇴근"]'::jsonb, 'published', now() + interval '25 days'),
('channel-fullstack', (SELECT id FROM companies WHERE slug='channel-corp'), '풀스택 엔지니어 (AI 메신저)', '개발', '서울 강남구', '원격', '경력 3년+', '학사 이상', 'AI 기반 고객 상담 메신저를 개발합니다.', '채널톡의 핵심 제품을 만듭니다.', '["React/Node.js 풀스택","AI 챗봇 통합","WebSocket"]'::jsonb, '["풀스택 경험","TypeScript","실시간 통신"]'::jsonb, '["원격근무","교육비","장비 지원"]'::jsonb, 'published', now() + interval '25 days');
