-- 자체 트래픽 이벤트 적재 테이블
-- 익명 INSERT 허용, SELECT는 admin only
-- 베타 시작 전 기반 마련

-- 1) 공통 enum/유틸은 따로 없음, 각 테이블 독립
create table if not exists public.job_views (
  id bigint generated by default as identity primary key,
  job_slug text not null,
  company_name text,
  category text,
  has_apply_url boolean,
  session_id uuid,
  created_at timestamptz not null default now()
);

create table if not exists public.apply_clicks (
  id bigint generated by default as identity primary key,
  job_slug text not null,
  company_name text,
  apply_url text,
  session_id uuid,
  created_at timestamptz not null default now()
);

create table if not exists public.company_views (
  id bigint generated by default as identity primary key,
  company_slug text not null,
  company_name text,
  category text,
  session_id uuid,
  created_at timestamptz not null default now()
);

create table if not exists public.search_events (
  id bigint generated by default as identity primary key,
  query text not null,
  surface text,
  session_id uuid,
  created_at timestamptz not null default now()
);

-- 인덱스: slug별 집계가 잦으므로 prefix
create index if not exists job_views_slug_idx on public.job_views (job_slug, created_at desc);
create index if not exists apply_clicks_slug_idx on public.apply_clicks (job_slug, created_at desc);
create index if not exists company_views_slug_idx on public.company_views (company_slug, created_at desc);
create index if not exists search_events_query_idx on public.search_events (query, created_at desc);

-- RLS 활성화
alter table public.job_views enable row level security;
alter table public.apply_clicks enable row level security;
alter table public.company_views enable row level security;
alter table public.search_events enable row level security;

-- INSERT는 anon/authenticated 모두 허용 (트래킹 목적)
-- 단, session_id 외 추가 식별자 못 받음 (개인정보 회피)
drop policy if exists "anyone can insert job_views" on public.job_views;
create policy "anyone can insert job_views" on public.job_views
  for insert to anon, authenticated with check (true);

drop policy if exists "anyone can insert apply_clicks" on public.apply_clicks;
create policy "anyone can insert apply_clicks" on public.apply_clicks
  for insert to anon, authenticated with check (true);

drop policy if exists "anyone can insert company_views" on public.company_views;
create policy "anyone can insert company_views" on public.company_views
  for insert to anon, authenticated with check (true);

drop policy if exists "anyone can insert search_events" on public.search_events;
create policy "anyone can insert search_events" on public.search_events
  for insert to anon, authenticated with check (true);

-- SELECT는 admin만 (is_platform_admin 함수 사용, 0001부터 존재)
drop policy if exists "admin can read job_views" on public.job_views;
create policy "admin can read job_views" on public.job_views
  for select to authenticated using (is_platform_admin());

drop policy if exists "admin can read apply_clicks" on public.apply_clicks;
create policy "admin can read apply_clicks" on public.apply_clicks
  for select to authenticated using (is_platform_admin());

drop policy if exists "admin can read company_views" on public.company_views;
create policy "admin can read company_views" on public.company_views
  for select to authenticated using (is_platform_admin());

drop policy if exists "admin can read search_events" on public.search_events;
create policy "admin can read search_events" on public.search_events
  for select to authenticated using (is_platform_admin());

comment on table public.job_views is '공고 상세 페이지 진입 이벤트. analytics.js의 trackJobView가 적재.';
comment on table public.apply_clicks is '"외부 사이트에서 지원하기" 버튼 클릭 이벤트.';
comment on table public.company_views is '회사 상세 페이지 진입 이벤트.';
comment on table public.search_events is '/jobs 검색창 입력 이벤트 (1초 debounce).';
